### ISSUE TITLE
创建表格时报,跪求解决方法

### ISSUE THREAD

**Issue by TopChina** [atorber/chatflow#60]
`维格表文件列表：
 {
  "新建表格": "dstuaVxfs3l0fgYZNQ"
}

   +  ChatFlow 17:16:14 GMT+0800 (China Standard Time) +
   |                                                   |
   |   表不存在，创建表并初始化数据...                 |
   |   qaSheet/问答列表|Qa                             |
   |                                                   |
   +---------------------------------------------------+

Request an error:  {
  success: false,
  code: 400,
  message: '[fields[启用状态|state].property]的值不正确'
}
系统表【问答列表|Qa】创建结果: [fields[启用状态|state].property]的值不正确
file:///root/chatflow/src/db/vika-db.ts:210
            throw new Error(`创建表【${sheet.name}】失败,启动中止，需要重新运行...`)
                  ^
Error: 创建表【问答列表|Qa】失败,启动中止，需要重新运行...
    at Function.init (file:///root/chatflow/src/db/vika-db.ts:210:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async init (file:///root/chatflow/src/chatflow.ts:46:3)
    at async main (file:///root/chatflow/example/ding-dong-bot.ts:27:3)`

**Comment by jacinzhang** [comment]
同错，求解决办法

**Comment by jacinzhang** [comment]
找到解决办法了，哪个表报错，在 vika 手动创建一下

**Comment by atorber** [comment]
这是因为维格表的创建表格api发生了breakingchange，最新的版本中已修复
